"""empty message

Revision ID: 93754ad8cdea
Revises: 942fea0eb4b0
Create Date: 2020-04-21 21:48:05.973535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93754ad8cdea'
down_revision = '942fea0eb4b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('prize_name', sa.String(length=128), nullable=True))
    op.create_foreign_key(None, 'prizes', 'category', ['prize_category'], ['id'])
    op.drop_column('prizes', 'name')
    op.drop_column('prizes', 'category')
    op.drop_column('prizes', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prizes', sa.Column('description', sa.VARCHAR(length=64000), nullable=True))
    op.add_column('prizes', sa.Column('category', sa.INTEGER(), nullable=True))
    op.add_column('prizes', sa.Column('name', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'prizes', type_='foreignkey')
    op.drop_column('prizes', 'prize_name')
    # ### end Alembic commands ###
